### ISSUE TITLE
A fj

### ISSUE THREAD

**Issue by Lolpprogamer666** [SilkePilon/OpenDeliveryBot#2]
A fun thing to add would be elytra fly so it can deliver faster :D

**Comment by SilkePilon** [comment]
Thx for the idea, we are working on this at the moment, but it's somewhat difficult because it's not "officially" supported by mineflayer. There is a pull request from a different user that we are trying to implement. We will keep you updated!

If you have any more suggestions please post them!

**Comment by Lolpprogamer666** [comment]
There is also mineflayer-elytrafly but its also easy to make it on your own just make it fly and then use phisics to push it forward and it will fly where it looks so in sky and then fly to coordinates while being in sky then land slowly i recommend elytrafly tho

**Comment by Lolpprogamer666** [comment]
it would also be nice if it kills itself using /kill or just walk into lava or something so it cant get tracked to base

**Comment by SilkePilon** [comment]
There is already an implementation for a self destruct. There is also a nice pull request that adds support for elytrafly. Also we are working on adding an user interface (web) to the bot as an option to the terminal
